In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

# PCA dla (-3,0),(-2,0),(-2,0),(5,0)

In [2]:
data = np.array([
    [-3, 0], 
    [-2, 0], 
    [-2, 0], 
    [5, 0]
    ])

data

array([[-3,  0],
       [-2,  0],
       [-2,  0],
       [ 5,  0]])

1. Wyznaczyć średnią arytmetyczną wymiaru `x` oraz `y`

In [3]:
mean_x = (data[0, 0] + data[1, 0] + data[2, 0]  + data[3, 0]) / 4
mean_y = (data[0, 1] + data[1, 1] + data[2, 1]  + data[3, 1]) / 4

(mean_x, mean_y)

(-0.5, 0.0)

2. Obliczenie macierzy kowariencji

` "The variance-covariance matrix is a square matrix with diagonal elements which represent the variance and the non-diagonal components that express covariance. The covariance of a variable can take any real value- positive, negative, or zero. A positive covariance suggests that the two variables have a positive relationship, whereas a negative covariance indicates that they do not. If two elements do not vary together, they have a zero covariance." `  
![](cov_matrix_formula.png)

In [4]:
cov_matrix = np.zeros((2, 2))

cov_matrix

array([[0., 0.],
       [0., 0.]])

Wzór na wariancje zbioru:  
![](variance_formula.png)  

Wzór na korelacje dwóch zbiorów:  
![](correlation_formula.png) 

In [5]:
# wariancja x
cov_matrix[0, 0] = (
    (data[0, 0] - mean_x)**2 + 
    (data[1, 0] - mean_x)**2 + 
    (data[2, 0] - mean_x)**2 + 
    (data[3, 0] - mean_x)**2 ) / 3

# wariancja y
cov_matrix[1, 1] = ( 
    (data[0, 1] - mean_y)**2 + 
    (data[1, 1] - mean_y)**2 + 
    (data[2, 1] - mean_y)**2 + 
    (data[3, 1] - mean_y)**2 ) / 3

# korelacja x i y
cov_matrix[0, 1] = (
    (data[0, 0] - mean_x) * (data[0, 1] - mean_y) +
    (data[1, 0] - mean_x) * (data[1, 1] - mean_y) +
    (data[2, 0] - mean_x) * (data[2, 1] - mean_y) +
    (data[3, 0] - mean_x) * (data[3, 1] - mean_y) ) / 3 

cov_matrix[1, 0] = cov_matrix[0, 1]


cov_matrix

array([[13.66666667,  0.        ],
       [ 0.        ,  0.        ]])

3. Obliczamy wartości własne  
![](eigen_formula.png)

In [6]:
# 𝜆 = ?  

# A_𝜆 = cov_matrix - 𝜆 * np.diag((2, 2)) 
 
# A_𝜆 = [[13.66666667,  0.        ],       [𝜆, 0]   [[13.66666667 - 𝜆,   0.        ],  
#        [ 0.        ,  0.        ]]   -   [0, 𝜆] =  [ 0.            ,  -𝜆.        ]]  

# det(A_𝜆) = (41/3 - 𝜆)(-𝜆) - 0*0 = 𝜆**2 - 41𝜆/3
# 𝜆**2 - 41𝜆/3 = 𝜆(𝜆 - 41/3)

# 𝜆 = 0 v 𝜆 = 41/3  <- wartosci wlasne

# 41/3 jest większe, więc będzie PC1

# Dla 𝜆 = 41/3 rozwiązać i znaleźć niezerowy wektror x:
# (cov_matrix - λI)x = 0

# [[0,     0],  [[x],    [[0],
#  [0, -41/3]] * [y]]  =  [0]]

# patrzcie jaką Kowalski jest kurwą ludzką, ze dal taki uklad rownan:



![](jakies_matematyczne_pierdolenie.png)

In [7]:
pca_vector = [1, 0]

nie ma chuja ze bym po policzyl jakbym dostal takie zadanie nieprzygotowany

In [8]:
projected_data = [
    (data[0,0] - mean_x) * pca_vector[0] + (data[0,1] - mean_y) * pca_vector[1],
    (data[1,0] - mean_x) * pca_vector[0] + (data[1,1] - mean_y) * pca_vector[1],
    (data[2,0] - mean_x) * pca_vector[0] + (data[2,1] - mean_y) * pca_vector[1],
    (data[3,0] - mean_x) * pca_vector[0] + (data[3,1] - mean_y) * pca_vector[1],
]

projected_data

[-2.5, -1.5, -1.5, 5.5]

# PCA dla (1,1), (0,0), (-2,-2), (3,3)

In [9]:

data = np.array([
    [1, 1], 
    [0, 0], 
    [-2, -2], 
    [3, 3]
    ])

data

array([[ 1,  1],
       [ 0,  0],
       [-2, -2],
       [ 3,  3]])

In [10]:
mean_x = (data[0, 0] + data[1, 0] + data[2, 0]  + data[3, 0]) / 4
mean_y = (data[0, 1] + data[1, 1] + data[2, 1]  + data[3, 1]) / 4

(mean_x, mean_y)

(0.5, 0.5)

In [11]:
cov_matrix = np.zeros((2, 2))

cov_matrix

array([[0., 0.],
       [0., 0.]])

In [12]:
# wariancja x
cov_matrix[0, 0] = (
    (data[0, 0] - mean_x)**2 + 
    (data[1, 0] - mean_x)**2 + 
    (data[2, 0] - mean_x)**2 + 
    (data[3, 0] - mean_x)**2 ) / 3

# wariancja y
cov_matrix[1, 1] = ( 
    (data[0, 1] - mean_y)**2 + 
    (data[1, 1] - mean_y)**2 + 
    (data[2, 1] - mean_y)**2 + 
    (data[3, 1] - mean_y)**2 ) / 3

# korelacja x i y
cov_matrix[0, 1] = (
    (data[0, 0] - mean_x) * (data[0, 1] - mean_y) +
    (data[1, 0] - mean_x) * (data[1, 1] - mean_y) +
    (data[2, 0] - mean_x) * (data[2, 1] - mean_y) +
    (data[3, 0] - mean_x) * (data[3, 1] - mean_y) ) / 3 

cov_matrix[1, 0] = cov_matrix[0, 1]


cov_matrix

array([[4.33333333, 4.33333333],
       [4.33333333, 4.33333333]])

In [16]:
# 𝜆 = ?  

# A_𝜆 = cov_matrix - 𝜆 * np.diag((2, 2)) 
 
# A_𝜆 = [[13/3,            13/3.         ],     [[𝜆, 0],   [[13/3 - 𝜆        ,       13/3        ],  
#        [ 13/3.        ,  13/3.        ]]   -   [0, 𝜆]] =  [13/3               ,  13/3-𝜆        ]]  

# det(A_𝜆) = (13/3 - 𝜆)**2 - (13/3)**2 = 169/9 - 26𝜆/3 + 𝜆**2 - 169/3 = -26𝜆/3 + 𝜆**2
# -26𝜆/3 + 𝜆**2 = 𝜆(-26/3 + 𝜆)

# 𝜆 = 0 v 𝜆 = 26/3  <- wartosci wlasne

# 26/3 jest większe, więc będzie PC1

# Dla 𝜆 = 26/3 rozwiązać i znaleźć niezerowy wektror x:
# (cov_matrix - λI)x = 0

# nadal nie zmienilem zdania 

![]()